name: CI

on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - closed
        branches:
            - main

jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ github.actor }}"

            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GH_TOKEN }}

            - run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com

            - name: Use Node.js 22.x
              uses: actions/setup-node@v5
              with:
                  node-version: 22
                  registry-url: "https://registry.npmjs.org"

            - run: npm ci

            - name: Lint
              run: npm run lint

            - name: Build
              run: npm run build

            - name: Bump version
              if: |
                  github.base_ref == 'main' &&
                  github.event.pull_request.merged == true
              run: echo "NEW_VERSION=$(npm --no-git-tag-version version minor)" >> $GITHUB_ENV

            - name: Commit package.json
              if: |
                  github.base_ref == 'main' &&
                  github.event.pull_request.merged == true
              uses: EndBug/add-and-commit@v9
              with:
                  message: Publish ${{ env.NEW_VERSION }}

            - name: Publish release
              if: |
                  github.base_ref == 'main' &&
                  github.event.pull_request.merged == true
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
