name: CI

on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - closed
        branches:
            - main

jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ github.actor }}"

            - uses: actions/checkout@v3
              with:
                  # TODO use vivid-planet-bot token here
                  token: ${{ secrets.GITHUB_TOKEN }}

            - run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com

            - name: Use Node.js 14.x
              uses: actions/setup-node@v3
              with:
                  node-version: 14
                  registry-url: "https://registry.npmjs.org"
                  cache: "yarn" # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies

            - run: yarn install

            - name: Lint
              run: yarn lint

            - name: Build
              run: yarn build

            - name: Bump version
              if: |
                  github.base_ref == 'main' &&
                  github.event.pull_request.merged == true
              run: npm --no-git-tag-version version minor

            - name: Commit package.json
              if: |
                  github.base_ref == 'main' &&
                  github.event.pull_request.merged == true
              uses: EndBug/add-and-commit@v9

            - name: Publish release
              if: |
                  github.base_ref == 'main' &&
                  github.event.pull_request.merged == true
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
